// samples/vue/src/js-sdk/ChannelList.vue
<script setup lang="ts">
import { reactive } from "vue"
import PubNub, { ChannelMetadataObject, ObjectCustom } from "pubnub";

const props = defineProps<{
  pubnub: PubNub
}>()

interface State {
  channels: ChannelMetadataObject<ObjectCustom>[];
  channelClickedNumber: number;
  nameInput: string;
}

const state: State = reactive({
  channels: [],
  channelClickedNumber: -1,
  nameInput: "",
})

async function loadChannels() {
  const channelsResponse = await props.pubnub.objects.getAllChannelMetadata();
  state.channels = channelsResponse.data.slice(0, 5);
}

function clickOnChannel(index: number) {
  state.channelClickedNumber = index;
}

async function editChannel() {
  await props.pubnub.objects.setChannelMetadata({
    channel: state.channels[state.channelClickedNumber].id,
    data: { name: state.nameInput },
  })

  state.channelClickedNumber = -1;
  state.nameInput = "";
  loadChannels();
}

async function deleteChannel(channelId: string) {
  await props.pubnub.objects.removeChannelMetadata({
    channel: channelId,
  });
  await loadChannels();
}

async function init() {
  loadChannels();
}

init();

</script>

<template>
  <div>
    <h1>
      channel list
    </h1>
    <ul>
      <li v-for="(channel, index) in state.channels" class="channel-row">
        <div v-if="index === state.channelClickedNumber">
          <input type="text" v-model="state.nameInput" />
          <button @click="editChannel()">Edit</button>
        </div>
        <div v-if="index !== state.channelClickedNumber">
          <span @click="clickOnChannel(index)">{{ channel.name || "No channel name provided" }}</span>
        </div>
        <button @click="deleteChannel(channel.id)">delete</button>
      </li>
    </ul>
  </div>
</template>

<style scoped>
  .channel-row {
    display: flex;
    flex-direction: row;
  }
</style>

// samples/angular/src/js-sdk/channel-list/channel-list.component.ts
import { Component, Input } from "@angular/core"
import PubNub, { ChannelMetadataObject, ObjectCustom } from "pubnub"

@Component({
  selector: "app-channel-list-sdk",
  templateUrl: "./channel-list.component.html",
  styleUrls: ["./channel-list.component.scss"],
})
export class ChannelListComponentSDK {
  @Input() pubnub!: PubNub
  channels: ChannelMetadataObject<ObjectCustom>[] = []
  channelClickedNumber = -1
  nameInput = ""

  async loadChannels() {
    const channelsResponse = await this.pubnub.objects.getAllChannelMetadata()
    this.channels = channelsResponse.data.slice(0, 5)
  }

  async ngOnInit() {
    this.loadChannels()
  }

  clickOnChannel(index: number) {
    this.channelClickedNumber = index
  }

  async editChannel() {
    await this.pubnub.objects.setChannelMetadata({
      channel: this.channels[this.channelClickedNumber].id,
      data: {
        name: this.nameInput,
      },
    })
    this.channelClickedNumber = -1
    this.nameInput = ""
    this.loadChannels()
  }

  async deleteChannel(channelId: string) {
    await this.pubnub.objects.removeChannelMetadata({
      channel: channelId,
    })
    await this.loadChannels()
  }
}

<div>
    <h1>
        channel list
    </h1>
    <p>
        Click on the channel name to edit it
    </p>
    <ul>
        <li *ngFor="let channel of channels; index as i" class="channel-row">
            <div *ngIf="i === channelClickedNumber">
                <input type="text" [(ngModel)]="nameInput" />
                <button (click)="editChannel()">Edit</button>
            </div>
            <div *ngIf="i !== channelClickedNumber">
                <span (click)="clickOnChannel(i)">{{ channel.name || "No channel name provided" }}</span>
            </div>
            <button (click)="deleteChannel(channel.id)">delete</button>
        </li>
    </ul>
</div>
