// sample/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import PubNub from "pubnub";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'angular';
  pubnubInput = "";
  channel = "test-channel";
  messages = [] as any[];
  typingReceived = false;
  typingSent = false;

  pubnub = new PubNub({
    subscribeKey: "demo",
    publishKey: "demo",
    userId: "test-user",
  })

  ngOnInit() {
    this.pubnub.subscribe({
      channels: [this.channel],
    });

    this.pubnub.addListener({
      message: (event) => {
        const { message } = event
        if (message.type === "text") this.messages.push(message)
      },
      signal: (event) => {
        const { message } = event
        if (message.type === "typing") this.typingReceived = message.value
      },
    })
  }

  async sendTyping(value: boolean) {
    await this.pubnub.signal({ channel: this.channel, message: { type: "typing", value } })
    this.typingSent = value
  }

  handleInput() {
    if (this.pubnubInput && !this.typingSent) {
      setTimeout(() => {
        console.log("stopped typing")
      }, 3000)
      this.sendTyping(true)
    }
    if (!this.pubnubInput && this.typingSent) this.sendTyping(false)
  }

  async handleSend() {
    await this.pubnub.publish({ channel: this.channel, message: { text: this.pubnubInput, type: "text" } })
    await this.sendTyping(false)
    this.pubnubInput = "";
  }
}

<div id="app">
  <div>
    <p>PubNub initialized with: {{ pubnub.getUUID() }}</p>
  </div>
  <div class="message-input">
    <h1>Message Input</h1>
    <input type="text" [(ngModel)]="pubnubInput" (ngModelChange)="handleInput()" />
    <button (click)="handleSend()">
    Send
  </button>
  </div>
  <div class="message-input">
    <h1>Typing Indicator</h1>
    <p *ngIf="typingReceived">{{ pubnub.getUUID() }} is typing...</p>
  </div>
  <div class="message-list">
    <h1>Message List</h1>
    <p *ngFor="let message of messages">{{ message.text }}</p>
  </div>
</div>

// sample/src/app.vue
<template>
  <div>
    <p>PubNub initialized with: {{ pubnub.getUUID() }}</p>
  </div>
  <div class="message-input">
    <h1>Message Input</h1>
    <input type="text" v-model="state.text" @input="handleInput" /><button @click="handleSend">
      Send
    </button>
  </div>
  <div class="message-input">
    <h1>Typing Indicator</h1>
    <p v-if="state.typingReceived">{{ pubnub.getUUID() }} is typing...</p>
  </div>
  <div class="message-list">
    <h1>Message List</h1>
    <p v-for="message in state.messages">{{ message.text }}</p>
  </div>
</template>

<script setup lang="ts">
import PubNub from "pubnub"
import { Chat } from "@pubnub/chat"
import { reactive } from "vue"

console.log("Chat SDK: ", Chat)

interface Message {
  text: string
  type: string
}

interface State {
  channel: string
  text: string
  messages: Message[]
  typingReceived: boolean
  typingSent: boolean
}

const state: State = reactive({
  channel: "test-channel",
  text: "",
  messages: [],
  typingReceived: false,
  typingSent: false,
})

const pubnub = new PubNub({
  subscribeKey: "demo",
  publishKey: "demo",
  userId: "test-user",
})

pubnub.addListener({
  message: (event) => {
    const { message } = event
    if (message.type === "text") state.messages.push(message)
  },
  signal: (event) => {
    const { message } = event
    if (message.type === "typing") state.typingReceived = message.value
  },
})

pubnub.subscribe({
  channels: [state.channel],
})

const sendTyping = async (value: boolean) => {
  await pubnub.signal({ channel: state.channel, message: { type: "typing", value } })
  state.typingSent = value
}

const handleInput = () => {
  if (state.text && !state.typingSent) {
    setTimeout(() => {
      console.log("stopped typing")
    }, 3000)
    sendTyping(true)
  }
  if (!state.text && state.typingSent) sendTyping(false)
}

const handleSend = async () => {
  await pubnub.publish({ channel: state.channel, message: { text: state.text, type: "text" } })
  await sendTyping(false)
  state.text = ""
}
</script>
