// samples/angular/src/app/app.component.ts
import { Component } from "@angular/core"
import PubNub from "pubnub"
import { Channel, Chat } from "@pubnub/chat"
import { StateService } from "./state.service"

const userId = "test-user"

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.scss"],
})
export class AppComponent {
  title = "angular"
  pubnubInput = ""
  messages = [] as any[]
  typingReceived = false
  typingSent = false
  channel: Channel | null = null
  forwardChannel: Channel | null = null

  constructor(private stateService: StateService) {}

  pubnub = new PubNub({
    publishKey: "demo",
    subscribeKey: "demo",
    userId,
  })

  chat = Chat.init({
    publishKey: "demo",
    subscribeKey: "demo",
    userId,
    typingTimeout: 2000,
  })

  async ngOnInit() {
    const user =
      (await this.chat.getUser(userId)) ||
      (await this.chat.createUser(userId, { name: "Some name" }))

    this.chat.setChatUser(user)
    const channel =
      (await this.chat.getChannel("test-channel-4")) ||
      (await this.chat.createChannel("test-channel-4", { name: "Some channel" }))

    await this.stateService.toggleChannel(channel)
    this.channel = this.stateService.currentChannel

    this.forwardChannel =
      (await this.chat.getChannel("forward-channel")) ||
      (await this.chat.createChannel("forward-channel", { name: "forward channel" }))
  }

  toggleCreateChannelModalChatSDK() {
    this.stateService.toggleCreateChannelModalChatSDK()
  }

  toggleCreateChannelModalJSSDK() {
    this.stateService.toggleCreateChannelModalJSSDK()
  }
}

<div id="app" class="flex">
  <div class="column" *ngIf="channel">
    <h1>SDK</h1>
    <div>
      <p>PubNub initialized with: {{ pubnub.getUUID() }}</p>
    </div>
    <app-message-input-sdk [pubnub]="pubnub" [channel]="channel.id" [typingSent]="typingSent" />
    <app-typing-indicator-sdk [typingReceived]="typingReceived" [pubnub]="pubnub" />
    <app-message-list-sdk [pubnub]="pubnub" [channel]="channel.id" />
    <app-create-channel-modal-sdk [pubnub]="pubnub" />
    <app-channel-list-sdk [pubnub]="pubnub" />
    <button (click)="toggleCreateChannelModalJSSDK()">Open create channel modal</button>
  </div>
  <div class="column" *ngIf="stateService.currentChannel && chat">
    <h1>Chat</h1>
    <div>
      <p>PubNub initialized with: {{ pubnub.getUUID() }}</p>
    </div>
    <app-message-input-chat [typingSent]="typingSent" [channel]="stateService.currentChannel" [chat]="chat" />
    <app-typing-indicator-chat [channel]="stateService.currentChannel" />
    <app-message-list-chat [channel]="stateService.currentChannel" [chat]="chat" />
    <app-create-channel-modal-chat [chat]="chat" />
    <app-channel-list-chat [chat]="chat" />
    <button (click)="toggleCreateChannelModalChatSDK()">Open create channel modal</button>
    <div *ngIf="forwardChannel">
      <app-message-list-chat [channel]="forwardChannel" [chat]="chat" />
    </div>
    <app-create-direct-conversation-modal-chat [chat]="chat" />
    <button (click)="toggleCreateDirectConversationModalChatSDK()">Open create direct conversation modal</button>
  </div>
</div>

// sample/vue/src/app.vue
<template>
  <div>
    <p>PubNub initialized with: {{ pubnub.getUUID() }}</p>
  </div>
  <div class="flex">
    <div class="column">
      <MessageInputSDK :pubnub="pubnub" :channel="channel.id" />
      <TypingIndicatorSDK :pubnub="pubnub" :channel="channel.id" />
      <MessageListSDK :pubnub="pubnub" :channel="channel.id" />
    </div>
    <div class="column">
      <MessageInputChat :chat="chat" :channel="channel" />
      <TypingIndicatorChat :chat="chat" :channel="channel" />
      <MessageListChat :chat="chat" :channel="channel" />
    </div>
  </div>
</template>

<script setup lang="ts">
import PubNub from "pubnub"
import { Chat } from "@pubnub/chat"
import MessageInputSDK from "./sdk/MessageInput.vue"
import MessageInputChat from "./chat/MessageInput.vue"
import TypingIndicatorSDK from "./sdk/TypingIndicator.vue"
import TypingIndicatorChat from "./chat/TypingIndicator.vue"
import MessageListSDK from "./sdk/MessageList.vue"
import MessageListChat from "./chat/MessageList.vue"

const userId = "test-user"
const channelId = "test-channel"

const pubnub = new PubNub({
  subscribeKey: "demo",
  publishKey: "demo",
  userId,
})

const chat = Chat.init({
  subscribeKey: "demo",
  publishKey: "demo",
  userId,
  typingTimeout: 2000,
})

const channel = chat.getChannel(channelId)
const user = chat.getUser(userId)
chat.setChatUser(user)
</script>

<style scoped>
.flex {
  display: flex;
}

.column {
  width: 50%;
}
</style>
