// samples/angular/src/chat-sdk/message-list/message-list.component.ts
import { Component, Input, SimpleChanges } from "@angular/core"
import { Channel, Chat, Message } from "@pubnub/chat"

@Component({
  selector: "app-message-list-chat",
  templateUrl: "./message-list.component.html",
  styleUrls: ["./message-list.component.scss"],
})
export class MessageListComponentChat {
  @Input() channel!: Channel
  @Input() chat!: Chat

  messages: Message[]
  isPaginationEnd: boolean

  constructor() {
    this.messages = []
    this.isPaginationEnd = false
  }

  async ngOnChanges(changes: SimpleChanges) {
    if (changes["channel"].previousValue) {
      changes["channel"].previousValue.disconnect()
    }
    if (changes["channel"].currentValue) {
      this.messages = []
      await changes["channel"].currentValue.join(
        (message: Message) => (this.messages = [...this.messages, message])
      )
    }
  }

  async loadMoreHistoricalMessages() {
    const historicalMessagesObject = await this.channel.getHistory({
      startTimetoken: this.messages?.[0]?.timetoken,
    })

    this.isPaginationEnd = !historicalMessagesObject.isMore

    this.messages = [...historicalMessagesObject.messages, ...this.messages]
  }

  async forwardMessage(message: Message) {
    const forwardChannel =
      (await this.chat.getChannel("forward-channel")) ||
      (await this.chat.createChannel("forward-channel", { name: "forward channel" }))

    await forwardChannel.forwardMessage(message)

    console.log("Message forwarded to:", forwardChannel.id)
  }

  async inviteSomeoneToThisChannel() {
    const someExistingUser =
      (await this.chat.getUser("Przemek")) ||
      (await this.chat.createUser("Przemek", { name: "Lukasz" }))

    const r = await this.channel.invite(someExistingUser)
  }
}

<div class="message-list">
    <h1>Message List</h1>
    <div>
        <div>
            <span>Channel pinned message: </span>
            <span>{{ pinnedMessages[channel.id] }}</span>
        </div>
        <div *ngFor="let message of messages">
            <div class="message-row">
                <div class="message-row__content">
                    <div *ngIf="message.quotedMessage">
                        <p>
                            Quoted message: {{ message.quotedMessage.text }}
                        </p>
                        <p>
                            Quote author: {{ message.quotedMessage.userId }}
                        </p>
                    </div>
                    <p *ngFor="let messagePart of message.getLinkedText()">
                        <span class="linked-text" [innerHTML]="renderMessagePart(messagePart) | byPassSecurity"></span>
                    </p>
                </div>
                <div class="message-row__toolbox">
                    <div class="message-row__forward-icon__container" (click)="forwardMessage(message)">
                        <img src="assets/forwardIcon.png" class="message-row__forward-icon" />
                    </div>
                    <div class="message-row__forward-icon__container" (click)="pinMessage(message)">
                        <img src="assets/star.png" class="message-row__forward-icon" />
                    </div>
                    <div class="message-row__forward-icon__container" (click)="loadThreadMessages(message)" *ngIf="message.hasThread">
                        <img src="assets/icon-of-blank-message-dialogue-box-free-vector.webp" class="message-row__forward-icon" />
                    </div>
                    <div class="message-row__forward-icon__container" (click)="quoteMessage(message)">
                        <img src="assets/quote-mark-icon-symbol-illustration-free-vector.jpeg" class="message-row__forward-icon" />
                    </div>
                </div>
            </div>
            <div class="message-row__thread-messages-container" *ngIf="threadMessages[message.timetoken]">
                <div *ngIf="message.hasThread">
                    <span>Thread pinned message: </span>
                    <span>{{ pinnedMessages[threadMessages[message.timetoken][0].channelId] }}</span>
                </div>
                <div *ngFor="let threadMessage of threadMessages[message.timetoken]">
                    <div class="message-row">
                        <p>
                            {{ threadMessage.content.text }}
                        </p>
                        <div class="message-row__forward-icon__container" (click)="forwardMessage(threadMessage)">
                            <img src="assets/forwardIcon.png" class="message-row__forward-icon" />
                        </div>
                        <div class="message-row__forward-icon__container" (click)="pinThreadMessage(threadMessage)">
                            <img src="assets/star.png" class="message-row__forward-icon" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <button [disabled]="isPaginationEnd" (click)="loadMoreHistoricalMessages()">Load more historical messages</button>
    <button (click)="inviteSomeoneToThisChannel()">Invite someone to this channel</button>
</div>

// samples/vue/src/chat-sdk/MessageList.vue
<script setup lang="ts">
import { Chat, Channel, Message } from "@pubnub/chat"
import { reactive } from "vue"

const props = defineProps<{
  chat: Chat
  channel: Channel
}>()

interface State {
  messages: Message[]
  isPaginationEnd: boolean
}

const state: State = reactive({
  messages: [],
  isPaginationEnd: false,
})

async function loadMoreHistoricalMessages() {
  const historicalMessagesObject = await props.channel.getHistory({ startTimetoken: state.messages?.[0]?.timetoken })

  state.isPaginationEnd = !historicalMessagesObject.isMore

  state.messages = [...historicalMessagesObject.messages, ...state.messages]
}

async function forwardMessage(message: Message) {
  const forwardChannel =
      (await props.chat.getChannel("forward-channel")) ||
      (await props.chat.createChannel("forward-channel", { name: "forward channel" }))

  await props.channel.forwardMessage(message, forwardChannel.id)

  console.log("Message forwarded to:", forwardChannel.id)
}

async function init() {
  await loadMoreHistoricalMessages()
  props.channel.connect((message) => state.messages.push(message))
}

init()
</script>

<template>
  <div class="message-list">
    <h1>Chat Message List</h1>
    <div>
      <div v-for="message in state.messages">
        <div class="message-row">
          <p>
            {{ message.content?.text || message.message?.text }}
          </p>
          <div class="message-row__forward-icon__container" @click="forwardMessage(message)">
            <img src="../assets/forwardIcon.png" class="message-row__forward-icon" />
          </div>
        </div>
      </div>
    </div>
    <button :disabled="state.isPaginationEnd" @click="loadMoreHistoricalMessages()">Load more historical messages</button>
  </div>
</template>

<style scoped>
  .message-row {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    max-width: 250px;
  }

  .message-row__forward-icon {
    width: 20px;
    height: 20px;
  }

  .message-row__forward-icon__container {
    cursor: pointer;
  }
</style>
