// sample/angular/src/chat/typing-indicator/typing-indicator.component.ts
import { Component, Input } from '@angular/core';
import { Channel } from "@pubnub/chat";
import PubNub from "pubnub";

@Component({
  selector: 'app-typing-indicator-chat',
  templateUrl: './typing-indicator.component.html',
  styleUrls: ['./typing-indicator.component.scss']
})
export class TypingIndicatorComponentChat {
  @Input() channel!: Channel;
  @Input() pubnub!: PubNub;
  typingReceived: boolean;

  constructor() {
    this.typingReceived = false;
  }

  ngOnInit() {
    this.channel.getTyping((value) => (this.typingReceived = value))
  }
}

<div class="typing-indicator">
    <h1>Typing Indicator</h1>
    <p *ngIf="typingReceived">{{ pubnub.getUUID() }} is typing...</p>
</div>

// samples/vue/src/chat-sdk/TypingIndicator.vue
<script setup lang="ts">
import { Chat, Channel } from "@pubnub/chat"
import { reactive } from "vue"

const props = defineProps<{
  chat: Chat
  channel: Channel
}>()

interface State {
  typingReceived: boolean
}

const state: State = reactive({
  typingReceived: false,
})

props.channel.getTyping((value) => (state.typingReceived = value))
</script>

<template>
  <div class="typing-indicator">
    <h1>Chat Typing Indicator</h1>
    <p v-if="state.typingReceived">{{ props.chat.sdk.getUUID() }} is typing...</p>
  </div>
</template>
