// samples/angular/src/js-sdk/message-list/message-list.component.ts
import { Component, Input } from "@angular/core"
import PubNub from "pubnub"

@Component({
  selector: "app-message-list-sdk",
  templateUrl: "./message-list.component.html",
  styleUrls: ["./message-list.component.scss"],
})
export class MessageListComponentSDK {
  @Input() pubnub!: PubNub
  @Input() channel!: string
  isPaginationEnd: boolean
  messages: any[]
  typingReceived = false

  constructor() {
    this.isPaginationEnd = false
    this.messages = []
  }

  async getHistory() {
    try {
      const options = {
        channels: [this.channel],
        count: 25,
        start: this.messages?.[0]?.timetoken,
        includeMessageActions: true,
        includeMeta: true,
      }

      const response = await this.pubnub.fetchMessages(options)

      this.isPaginationEnd = response.channels[this.channel].length !== 25
      this.messages = [...response.channels[this.channel], ...this.messages]
    } catch (error) {
      throw error
    }
  }

  async ngOnInit() {
    await this.getHistory()

    this.pubnub.subscribe({
      channels: [this.channel],
    })

    this.pubnub.addListener({
      message: (event) => {
        const { message } = event
        if (message.type === "text") this.messages.push(message)
      },
      signal: (event) => {
        const { message } = event
        if (message.type === "typing") this.typingReceived = message.value
      },
    })
  }
}

<div class="message-list">
    <h1>Message List</h1>
    <p *ngFor="let message of messages">{{ message.message?.text || message.text }}</p>
    <button [disabled]="isPaginationEnd" (click)="getHistory()">Load more historical messages</button>
</div>

// samples/vue/src/js-sdk/MessageList.vue
<script setup lang="ts">
import PubNub, { FetchMessagesResponse } from "pubnub"
import { reactive } from "vue"

interface Message {
  text: string
  type: string
  timetoken: string
}

const props = defineProps<{
  pubnub: PubNub
  channel: string
}>()

interface State {
  messages: FetchMessagesResponse["channels"]["channel"]
  isPaginationEnd: boolean
}

const state: State = reactive({
  messages: [],
  isPaginationEnd: false,
})

async function getHistory() {
  try {
    const options = {
      channels: [props.channel],
      count: 25,
      start: state.messages?.[0]?.timetoken || undefined,
      includeMessageActions: true,
      includeMeta: true,
    };

    const response = await props.pubnub.fetchMessages(options);

    state.isPaginationEnd = response.channels[props.channel].length !== 25
    state.messages = [...response.channels[props.channel], ...state.messages]
  } catch(error) {
    throw error
  }
}

async function init() {
  await getHistory()

  props.pubnub.addListener({
    message: (event) => {
      const { message } = event
      if (message.type === "text") state.messages.push(message)
    },
  })

  props.pubnub.subscribe({
    channels: [props.channel],
  })
}

init()

</script>

<template>
  <div class="message-list">
    <h1>SDK Message List</h1>
    <p v-for="message in state.messages">{{ message.message.text }}</p>
    <button :disabled="state.isPaginationEnd" @click="getHistory()">Load more historical messages</button>
  </div>
</template>
