// sample/vue/src/sdk/MessageInput.vue
<script setup lang="ts">
import PubNub from "pubnub"
import { reactive } from "vue"

const props = defineProps<{
  pubnub: PubNub
  channel: string
}>()

interface State {
  text: string
  typingSent: boolean
}

const state: State = reactive({
  text: "",
  typingSent: false,
})

const sendTyping = async (value: boolean) => {
  await props.pubnub.signal({ channel: props.channel, message: { type: "typing", value } })
  state.typingSent = value
}

const handleInput = () => {
  if (state.text && !state.typingSent) sendTyping(true)
  if (!state.text && state.typingSent) sendTyping(false)
}

const handleSend = async () => {
  await props.pubnub.publish({
    channel: props.channel,
    message: { text: state.text, type: "text" },
  })
  await sendTyping(false)
  state.text = ""
}
</script>

<template>
  <div class="message-input">
    <h1>SDK Message Input</h1>
    <input type="text" v-model="state.text" @input="handleInput" />
    <button @click="handleSend">Send</button>
  </div>
</template>

// samples/angular/src/js-sdk/message-input/message-input.component.ts
import { Component, Input } from '@angular/core';
import PubNub from "pubnub";

@Component({
  selector: 'app-message-input-sdk',
  templateUrl: './message-input.component.html',
  styleUrls: ['./message-input.component.scss']
})
export class MessageInputComponentSDK {
  pubnubInput = "";
  @Input() channel!: string;
  @Input() pubnub!: PubNub;
  @Input() typingSent!: boolean;


  async sendTyping(value: boolean) {
    await this.pubnub.signal({ channel: this.channel, message: { type: "typing", value } })
    this.typingSent = value
  }

  handleInput() {
    if (this.pubnubInput && !this.typingSent) {
      setTimeout(() => {
        console.log("stopped typing")
      }, 3000)
      this.sendTyping(true)
    }
    if (!this.pubnubInput && this.typingSent) this.sendTyping(false)
  }

  async handleSend() {
    await this.pubnub.publish({ channel: this.channel, message: { text: this.pubnubInput, type: "text" } })
    await this.sendTyping(false)
    this.pubnubInput = "";
  }
}

<div class="message-input">
    <h1>Message Input</h1>
    <input type="text" [(ngModel)]="pubnubInput" (ngModelChange)="handleInput()" />
    <button (click)="handleSend()">
        Send
    </button>
</div>
