// samples/vue/src/chat-sdk/ChannelList.vue
<script setup lang="ts">
import { Channel, Chat } from "@pubnub/chat"
import { reactive } from "vue"

const props = defineProps<{
  chat: Chat
}>()

interface State {
  channels: Channel[]
  channelClickedNumber: number;
  nameInput: string;
}

const state: State = reactive({
  channels: [],
  channelClickedNumber: -1,
  nameInput: "",
})

async function loadChannels() {
  state.channels = await props.chat.getChannels();
}

function clickOnChannel(index: number) {
  state.channelClickedNumber = index;
}

async function editChannel() {
  await state.channels[state.channelClickedNumber].update({ name: state.nameInput });
  state.channelClickedNumber = -1;
  state.nameInput = "";
  loadChannels();
}

async function deleteChannel(channelId: string) {
  await props.chat.deleteChannel(channelId);
  await loadChannels();
}

async function init() {
  loadChannels();
}

init();

</script>

<template>
  <div>
    <h1>
      channel list
    </h1>
    <ul>
      <li v-for="(channel, index) in state.channels" class="channel-row">
        <div v-if="index === state.channelClickedNumber">
          <input type="text" v-model="state.nameInput" />
          <button @click="editChannel()">Edit</button>
        </div>
        <div v-if="index !== state.channelClickedNumber">
          <span @click="clickOnChannel(index)">{{ channel.name || "No channel name provided" }}</span>
        </div>
        <button @click="deleteChannel(channel.id)">delete</button>
      </li>
    </ul>
  </div>
</template>

<style scoped>
  .channel-row {
    display: flex;
    flex-direction: row;
  }
</style>

// samples/angular/src/chat-sdk/channel-list/channel-list.component.ts
import { Component, Input } from "@angular/core"
import { Channel, Chat } from "@pubnub/chat"

@Component({
  selector: "app-channel-list-chat",
  templateUrl: "./channel-list.component.html",
  styleUrls: ["./channel-list.component.scss"],
})
export class ChannelListComponentChat {
  @Input() chat!: Chat
  channels: Channel[] = []
  channelClickedNumber = -1
  nameInput = ""

  async loadChannels() {
    this.channels = await this.chat.getChannels()
  }

  async ngOnInit() {
    this.loadChannels()
  }

  clickOnChannel(index: number) {
    this.channelClickedNumber = index
  }

  async editChannel() {
    await this.channels[this.channelClickedNumber].update({ name: this.nameInput })
    this.channelClickedNumber = -1
    this.nameInput = ""
    this.loadChannels()
  }

  async deleteChannel(channelId: string) {
    await this.chat.deleteChannel(channelId)
    await this.loadChannels()
  }
}

<div>
    <h1>
        channel list
    </h1>
    <p>
        Click on the channel name to edit it
    </p>
    <ul>
        <li *ngFor="let channel of channels; index as i" class="channel-row">
            <div *ngIf="i === channelClickedNumber">
                <input type="text" [(ngModel)]="nameInput" />
                <button (click)="editChannel()">Edit</button>
            </div>
            <div *ngIf="i !== channelClickedNumber" class="channel-info">
                <span>Channel id: {{ channel.id }}</span>
                <span (click)="clickOnChannel(i)">{{ channel.name || "No channel name provided" }}</span>
            </div>
            <button (click)="deleteChannel(channel.id)">delete</button>
            <button (click)="toggleChannel(channel.id)">{{ buttonTexts[channel.id] || "Join" }}</button>
        </li>
    </ul>
</div>
