// samples/angular/src/app/app.component.ts
import { Component } from "@angular/core"
import PubNub from "pubnub"
import { Channel, Chat } from "@pubnub/chat"
import { StateService } from "./state.service"

const userId = "test-user"

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.scss"],
})
export class AppComponent {
  title = "angular"
  pubnubInput = ""
  messages = [] as any[]
  typingReceived = false
  typingSent = false
  channel: Channel | null = null
  forwardChannel: Channel | null = null

  constructor(private stateService: StateService) {}

  pubnub = new PubNub({
    publishKey: "demo",
    subscribeKey: "demo",
    userId,
  })

  chat = Chat.init({
    publishKey: "demo",
    subscribeKey: "demo",
    userId,
    typingTimeout: 2000,
  })

  async ngOnInit() {
    const user =
      (await this.chat.getUser(userId)) ||
      (await this.chat.createUser(userId, { name: "Some name" }))

    this.chat.setChatUser(user)
    const channel =
      (await this.chat.getChannel("test-channel-4")) ||
      (await this.chat.createChannel("test-channel-4", { name: "Some channel" }))

    await this.stateService.toggleChannel(channel)
    this.channel = this.stateService.currentChannel

    this.forwardChannel =
      (await this.chat.getChannel("forward-channel")) ||
      (await this.chat.createChannel("forward-channel", { name: "forward channel" }))
  }

  toggleCreateChannelModalChatSDK() {
    this.stateService.toggleCreateChannelModalChatSDK()
  }

  toggleCreateChannelModalJSSDK() {
    this.stateService.toggleCreateChannelModalJSSDK()
  }
}

<div id="app" class="flex">
  <div class="column" *ngIf="channel">
    <h1>SDK</h1>
    <div>
      <p>PubNub initialized with: {{ pubnub.getUUID() }}</p>
    </div>
    <app-message-input-sdk [pubnub]="pubnub" [channel]="channel.id" [typingSent]="typingSent" />
    <app-typing-indicator-sdk [typingReceived]="typingReceived" [pubnub]="pubnub" />
    <app-message-list-sdk [pubnub]="pubnub" [channel]="channel.id" />
    <app-create-channel-modal-sdk [pubnub]="pubnub" />
    <app-channel-list-sdk [pubnub]="pubnub" />
    <button (click)="toggleCreateChannelModalJSSDK()">Open create channel modal</button>
  </div>
  <div class="column" *ngIf="stateService.currentChannel && chat">
    <h1>Chat</h1>
    <div>
      <p>PubNub initialized with: {{ pubnub.getUUID() }}</p>
    </div>
    <app-message-input-chat [typingSent]="typingSent" [channel]="stateService.currentChannel" [chat]="chat" />
    <app-typing-indicator-chat [channel]="stateService.currentChannel" />
    <app-message-list-chat [channel]="stateService.currentChannel" [chat]="chat" />
    <app-create-channel-modal-chat [chat]="chat" />
    <app-channel-list-chat [chat]="chat" />
    <button (click)="toggleCreateChannelModalChatSDK()">Open create channel modal</button>
    <div *ngIf="forwardChannel">
      <app-message-list-chat [channel]="forwardChannel" [chat]="chat" />
    </div>
    <app-create-direct-conversation-modal-chat [chat]="chat" />
    <button (click)="toggleCreateDirectConversationModalChatSDK()">Open create direct conversation modal</button>
  </div>
</div>

// samples/vue/src/app.vue
<template>
  <div>
    <p>PubNub initialized with: {{ pubnub.getUUID() }}</p>
  </div>
  <div class="flex" v-if="state.channel">
    <div class="column">
      <MessageInputSDK :pubnub="pubnub" :channel="state.channel.id" />
      <TypingIndicatorSDK :pubnub="pubnub" :channel="state.channel.id" />
      <MessageListSDK :pubnub="pubnub" :channel="state.channel.id" />
      <CreateChannelModalSDK :pubnub="pubnub" :toggleCreateChannelModal="toggleCreateChannelModalJSSDK" :createChannelModalOpen="state.createChannelModalJSSDKOpen" />
      <ChannelListSDK :pubnub="pubnub" />
      <button @click="toggleCreateChannelModalJSSDK">Open create channel modal</button>
    </div>
    <div class="column">
      <MessageInputChat :chat="chat" :channel="state.channel" />
      <TypingIndicatorChat :chat="chat" :channel="state.channel" />
      <MessageListChat :chat="chat" :channel="state.channel" />
      <CreateChannelModalChat :chat="chat" :toggleCreateChannelModal="toggleCreateChannelModalChatSDK" :createChannelModalOpen="state.createChannelModalChatsSDKOpen" />
      <ChannelListChat :chat="chat" />
      <button @click="toggleCreateChannelModalChatSDK">Open create channel modal</button>
      <div v-if="state.forwardChannel">
        <MessageListChat :chat="chat" :channel="state.forwardChannel" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import PubNub from "pubnub"
import { Channel, Chat } from "@pubnub/chat"
import MessageInputSDK from "./js-sdk/MessageInput.vue"
import MessageInputChat from "./chat-sdk/MessageInput.vue"
import TypingIndicatorSDK from "./js-sdk/TypingIndicator.vue"
import TypingIndicatorChat from "./chat-sdk/TypingIndicator.vue"
import MessageListSDK from "./js-sdk/MessageList.vue"
import MessageListChat from "./chat-sdk/MessageList.vue"
import CreateChannelModalChat from "./chat-sdk/CreateChannelModal.vue"
import ChannelListChat from "./chat-sdk/ChannelList.vue"
import ChannelListSDK from "./js-sdk/ChannelList.vue"
import CreateChannelModalSDK from "./js-sdk/CreateChannelModal.vue"
import { reactive } from "vue";

interface State {
  channel?: Channel
  forwardChannel?: Channel
  createChannelModalJSSDKOpen: boolean;
  createChannelModalChatsSDKOpen: boolean;
}

const userId = "test-user"
const channelId = "test-channel"

const pubnub = new PubNub({
  publishKey: "demo",
  subscribeKey: "demo",
  userId,
})

const chat = Chat.init({
  publishKey: "demo",
  subscribeKey: "demo",
  userId,
  typingTimeout: 2000,
})

const state: State = reactive({
  channel: undefined,
  forwardChannel: undefined,
  createChannelModalJSSDKOpen: false,
  createChannelModalChatsSDKOpen: false,
});

(async function() {
  const user =
      (await chat.getUser(userId)) ||
      (await chat.createUser(userId, { name: "Some name" }))

  chat.setChatUser(user)
  state.channel =
      (await chat.getChannel("test-channel")) ||
      (await chat.createChannel("test-channel", { name: "Some channel" }))

  state.forwardChannel =
      (await chat.getChannel("forward-channel")) ||
      (await chat.createChannel("forward-channel", { name: "forward channel" }))
})();

const toggleCreateChannelModalJSSDK = () => {
  state.createChannelModalJSSDKOpen = !state.createChannelModalJSSDKOpen;
}

const toggleCreateChannelModalChatSDK = () => {
  state.createChannelModalChatsSDKOpen = !state.createChannelModalChatsSDKOpen;
}

</script>

<style scoped>
.flex {
  display: flex;
}

.column {
  width: 50%;
}
</style>
