// samples/angular/src/chat-sdk/typing-indicator/typing-indicator.component.ts
import { Component, Input } from "@angular/core"
import { Channel, TypingData } from "@pubnub/chat"
import PubNub from "pubnub"

@Component({
  selector: "app-typing-indicator-chat",
  templateUrl: "./typing-indicator.component.html",
  styleUrls: ["./typing-indicator.component.scss"],
})
export class TypingIndicatorComponentChat {
  @Input() channel!: Channel
  @Input() pubnub!: PubNub
  typingData: TypingData[] = []

  ngOnInit() {
    this.channel.getTyping((value) => (this.typingData = value))
  }
}

<div class="typing-indicator">
    <h1>Typing Indicator</h1>
    <p *ngFor="let typing of typingData">{{ typing.name }} is typing...</p>
</div>

// sample/vue/src/chat/TypingIndicator.vue
<script setup lang="ts">
import { Chat, Channel, TypingData } from "@pubnub/chat"
import { ref } from "vue"

const props = defineProps<{
  chat: Chat
  channel: Channel
}>()

type NameCustom = { name: string }

let typingData = ref<TypingData<NameCustom>[]>([])

props.channel.getTyping<NameCustom>((data) => (typingData.value = data))
</script>

<template>
  <div class="typing-indicator">
    <h1>Chat Typing Indicator</h1>
    <p v-for="typing in typingData">{{ typing.data?.name }} is typing...</p>
  </div>
</template>
